### ISSUE TITLE
Error loading postrender module action-watermark: ReferenceError: options is not defined

### ISSUE THREAD

**Issue by michielst** [AbdulBsit/action-watermark#3]
After installing the package globally and using the example postrender action i receive the following error after the postrender has started:

`
[Qq_qo7-nf2NNTpxqi6sOD] applying postrender actions...
Error: Error loading postrender module action-watermark: ReferenceError: options is not defined
    at /Users/michiel/Documents/projects/project/node_modules/@nexrender/core/src/tasks/actions.js:25:35
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
`

Is this package still up to date?

**Comment by AbdulBsit** [comment]
Yes package is not up to date , i will update it tomorrow , it will be fixed then
